"""Script to test the adx.py module."""
# TODO: Convert to actual unit test!

from exports.adx import ADXFile
import time

start = time.time()
export_file = ADXFile("../export.adx")
# this test data ends at line 410
data = [
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
    {
        "name": "Galen Gold",
        "call": "KB6EE",
        "frequency": 32.1532,
        "signal": "59",
        "snr": 26,
        "mode": "LSB",
    },
    {
        "name": "Some Guy",
        "call": "A2BCD",
        "frequency": 376.1532,
        "signal": "59",
        "snr": -12,
        "mode": "FT8",
    },
    {
        "name": "Hammie Operatori",
        "call": "K8HAM",
        "frequency": 0.1424,
        "signal": "353",
        "snr": -6,
        "mode": "CW",
    },
    {
        "name": "test2",
        "call": "testcall2",
        "frequency": 22.2222,
        "signal": "22",
        "snr": 22,
        "mode": "DM2",
    },
    {
        "name": "test3",
        "call": "testcall3",
        "frequency": 33.3333,
        "signal": "33",
        "snr": 33,
        "mode": "AM3",
    },
]
# this data started at line 10

export_file.write_header()
for x in data:
    export_file.write_record(x)
export_file.write_file()
end = time.time()
print(f"done! ({end-start})")
